CC = g++ -pedantic -pedantic-errors -O3 -Wall
target = RunApp

RunApp: RunApp.cpp Address.cpp FinnishAddress.cpp FinnishAddrFactory.cpp
	$(CC) -o $@ RunApp.cpp Address.cpp FinnishAddress.cpp FinnishAddrFactory.cpp
